[package]
name = "Cyphers"
version = "0.1.0"
edition = "2021"

[dependencies]
magma = {path = "magma"}
DES = {path = "DES"}
traits = {path = "traits"}
AES = {path = "AES"}
Kuznechik = {path = "Kuznechik"}

[profile.release]
debug = true